@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20

participant "Client Application" as Client
actor User
box Service
boundary Main
control Route
control RequestHandler <<Actor>>
control Supervisor <<Actor>>
control Server <<Actor>>
control Master <<Actor>>
control ReducersGroup <<Actor>>
control MappersGroup <<Actor>>
control MappersGroupQuery <<Actor>>
control ReducersGroupQuery <<Actor>>
control ReduceWorker <<Actor>>
control MapWorker <<Actor>>
collections MemCache
end box
database Mongo
boundary "Google Geolocation API" as GGA

autonumber "<b>[000]"

== Initialization ==

User -> Main : Initializes System
activate Main

Main -> Supervisor : Creates actor
activate Supervisor
Main -> Supervisor : Sends "CreateInfrastructure" message

Supervisor -> Server : Creates actor
activate Server
Supervisor -> Server : Sends "CreateInfrastructure" message

Server -> Master : Creates actor
activate Master
Server -> Master : Sends "CreateInfrastructure" message

Master -> ReducersGroup : Creates actor
activate ReducersGroup
Master -> ReducersGroup : Sends "RequestTrackReducer" message

ReducersGroup -> ReducersGroup : Checks if ReducerWorker with given name exists

opt false
ReducersGroup -> ReduceWorker : Creates actor
activate ReduceWorker
end

ReducersGroup -> ReduceWorker : Sends "RequestTrackReducer" message

ReduceWorker --> ReducersGroup : Sends "ReducerRegistered" message

Master -> MappersGroup : Creates actor
activate MappersGroup
Master -> MappersGroup : Sends "RequestTrackMapper" message

MappersGroup -> MappersGroup : Checks if MapWorker with given name exists

opt false
MappersGroup -> MapWorker : Creates actor
activate MapWorker
end

MappersGroup -> MapWorker : Sends "RequestTrackMapper" message

MapWorker --> MappersGroup : Sends "MapperRegistered" signal

Main -> Route : Initializes Route
activate Route

== Runtime ==

Client -> Route : Invokes "getDirections" endpoint

Route -> RequestHandler : Creates actor
activate RequestHandler
Route -> RequestHandler : Sends request

RequestHandler -> Supervisor : Sends "CalculateDirections" signal

Supervisor -> Server : Forwards request

Server -> Master : Forwards request

Master -> MappersGroup : Forwards request

MappersGroup -> MappersGroupQuery : Creates actor
activate MappersGroupQuery

MappersGroup -> MappersGroupQuery : Forwards request

MappersGroupQuery -> MapWorker : Forwards request

alt MapWorker responds with result

MapWorker -> MappersGroupQuery : Sends map result

MappersGroupQuery -> MappersGroupQuery : Stops self

else MapWorker terminates

MapWorker -> MappersGroupQuery : Sends "Terminated" signal

MappersGroupQuery -> MappersGroupQuery : Stops self

else Responses collection times out

MappersGroupQuery -> MappersGroupQuery : Stops self

end

MappersGroupQuery -> Master : Sends "RespondAllMapResults" message

deactivate MappersGroupQuery

Master -> ReducersGroup : Sends "CalculateReduction" message

ReducersGroup -> ReducersGroupQuery : Creates actor
activate ReducersGroupQuery

ReducersGroupQuery -> ReduceWorker : Forwards request

alt ReduceWorker responds with result

ReduceWorker -> ReducersGroupQuery : Sends reduce result

ReducersGroupQuery -> ReducersGroupQuery : Stops self

else ReduceWorker terminates

ReduceWorker -> ReducersGroupQuery : Sends "Terminated" signal

ReducersGroupQuery -> ReducersGroupQuery : Stops self

else Responses collection times out

ReducersGroupQuery -> ReducersGroupQuery : Stops self

end

ReducersGroupQuery -> Master : Sends "RespondAllReduceResults" message

deactivate ReducersGroupQuery

Master -> Master : Calculates euclidean minimum

Master -> RequestHandler : Sends result

RequestHandler -> Client : Sends result
deactivate RequestHandler

== Shutdown ==

User -> Main : Submits any input

Main -> Main : Terminates Actor System
Main -> Supervisor : Terminate
Supervisor -> Server : Terminate
Server -> Master : Terminate
Master -> MappersGroup : Terminate
MappersGroup -> MapWorker : Terminate
deactivate MapWorker
Master -> ReducersGroup : Terminate
ReducersGroup -> ReduceWorker : Terminate
deactivate MappersGroup
deactivate ReduceWorker
deactivate ReducersGroup
deactivate Master
deactivate Server
deactivate Supervisor
deactivate Main

@enduml